#!/bin/bash

# Usage - any other invocation will cause an error at the docker pull stage:
# bioc-docker release
# bioc-docker devel

version=$1

docker pull bioconductor/"$version"_core2

mkdir -p "~/.docker-$version-packages"

docker run -e PASSWORD=rstudiopassword \
      -v ~/git:/home/rstudio/git  \
      -v ~/.docker-"$version"-packages:/usr/local/lib/R/host-site-library \
      -p 8787:8787 \
      bioconductor/"$version"_core2

# Note, currently you must enter the following command in the R console to attach the host site library:
# > .libPaths(c("/usr/local/lib/R/host-site-library", .libPaths()))
